Vagrant.configure("2") do |config|
  config.vm.box = "amzn2base"
  config.ssh.insert_key = false
  config.ssh.username = "ec2-user"
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
